services:
  mysql:
    image: mysql:8.4.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=maek_dev
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: