services:
  postgres:
    image: postgres:17.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=maek_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passwd
    volumes:
      - pg_data:/var/lib/postgresql/data

  postgres-test:
    image: postgres:17.2
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=maek_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passwd

volumes:
  pg_data: