[settings]
experimental = true

[env]
ROOT = '{{env.HOME}}/code/karngyan/maek'
RUN_MODE = 'dev'
SERVER_PORT = '8080'

SQL_CONN = 'postgres://maek:passwd@localhost:5432/maek_dev?sslmode=disable'
SQL_CONN_TEST = 'postgres://maek:passwd@localhost:5433/maek_test?sslmode=disable'
ATLAS_TMP_DEV_URL = 'docker://postgres/17.2/dev'

# Basically the domains on which the app is hosted separated by semicolons
CORS_ALLOWED_ORIGINS = 'http://localhost:3000'

# CGO_ENABLED is set to 0 to disable cgo
CGO_ENABLED = '0'

[tools]
go = '1.23.1'
atlas = '0.29.0'
node = '20.17.0'
'npm:pnpm' = '9.12.1'

'go:github.com/beego/bee/v2' = '2.3.0'
