[settings]
experimental = true

[env]
ROOT = '{{env.HOME}}/code/karngyan/maek'
RUN_MODE = 'dev'
SERVER_PORT = '8080'
POSTGRES_HOST = 'localhost'
POSTGRES_PORT = '5432'
POSTGRES_USER = 'postgres'
POSTGRES_PASSWORD = 'passwd'
POSTGRES_DB = 'maek_dev'

POSTGRES_URL = 'postgres://{{env.POSTGRES_USER}}:{{env.POSTGRES_PASSWORD}}@{{env.POSTGRES_HOST}}:{{env.POSTGRES_PORT}}/{{env.POSTGRES_DB}}?sslmode=disable'

# test db settings
POSTGRES_TEST_PORT = '5433'
POSTGRES_TEST_DB = 'maek_test'

# Basically the domains on which the app is hosted separated by semicolons
CORS_ALLOWED_ORIGINS = 'http://localhost:3000'

# CGO_ENABLED is set to 0 to disable cgo
CGO_ENABLED = '0'

[tools]
go = '1.23.1'
atlas = '0.29.0'
node = '20.17.0'
'npm:pnpm' = '9.12.1'

'go:github.com/beego/bee/v2' = '2.3.0'
